### PR TITLE
 Add a --keep-v option to not drop `v` at the beginning of version numbers

### PR DESCRIPTION
**Pull request by samoht**
/cc @diml 

I've done a minimal amount of testing with sexplib0 with `dune-release distrib --keep-v` and `dune-release opam --keep-v` and that seems to work fine.

### CODE REVIEW

**Comment by diml** [comment]
Thanks!

One thing I'm thinking is that keeping the v prefix is a property of the package. Would it be possible for this setting to be persistent? For instance by writing `x-keep-v-prefix: true` in th opam file

**Comment by diml** [comment]
Another idea: we are currently moving forward with the renaming (https://github.com/ocaml/dune/pull/721) and have started adding support for `dune-project` files. There will be a `(version ...)` stanza in this file. Whether we want the `v` prefix or not could be derived from this stanza. For instance you'd write `(version %%VERSION%%)` (the default) to keep the `v` prefix and `(version %%VERSION_NUM%%)` to drop it.

We can expose and API in dune to parse this file so that dune-release can access this information easily. What do you think?

**Comment by samoht** [comment]
> We can expose and API in dune to parse this file so that dune-release can access this information easily. What do you think?

That seems a good idea. Having `x-keep-v-prefix: true` looks like a hack and I am not sure opam 1.2 will be happy with that.

**Comment by samoht** [comment]
Merging from now, we will look at how to persist the option later.

**Pull request merged**
