### PR TITLE
Remove the delegate API

### PR DESCRIPTION
**Pull request by gpetiot**
As discussed offline, this API was not used by most users and was over-complicating the code.

### CODE REVIEW

**Comment by samoht** [comment]
Hum wait, this is useful for people not using GitHub to store their release tarballs. Can you please post at least a summary of your discussions before removing that completely?

**Comment by NathanReb** [comment]
Sure! I'll do that today.

I also suggest we go through a deprecation phase beforehand so we give users of that feature a chance to express themselves!

**Comment by gpetiot** [comment]
#154 for more context

**Comment by NathanReb** [comment]
I wrote an issue with a proposed plan here: https://github.com/samoht/dune-release/issues/188.

I suggest we close this PR for now as the plan to remove delegates requires quite a few steps and it's likely it will take us some time (hopefully only a few months) to actually remove the code.

**Pull request closed without merging**
